async page => {
  const name = page.getByLabel('Name')
  const email = page.getByLabel('Email Address')
  const send = page.getByRole('button', { name: /Send Message|Sending Message/ })

  await page.getByRole('heading', { name: 'Contact Us' }).waitFor()
  await page.getByText('STUDIO').waitFor()
  await page.getByText('Work', { exact: true }).waitFor()
  await page.getByText('About', { exact: true }).waitFor()
  await page.getByText('Contact', { exact: true }).waitFor()
  await page.getByText('Have a question or want to work together? Drop us a line.').waitFor()

  await send.click()
  await page.getByText('Name is required.').waitFor()
  await page.getByText('Email address is required.').waitFor()
  await name.fill('a'.repeat(101))
  await email.fill('invalid-email')
  await send.click()
  await page.getByText('Name must be 100 characters or fewer.').waitFor()
  await page.getByText('Enter a valid email address.').waitFor()
  await name.fill('A')
  await email.fill('a@example.com')
  await send.click()
  await page.getByRole('heading', { name: 'Thank you!' }).waitFor()
  await page.getByText("Your information has been successfully submitted. We'll be in touch shortly.").waitFor()
  await page.getByRole('button', { name: 'Back to Home' }).click()
  await page.getByRole('heading', { name: 'Contact Us' }).waitFor()

  await name.fill('B')
  await email.fill(`${'a'.repeat(64)}@${'b'.repeat(63)}.${'c'.repeat(63)}.${'d'.repeat(61)}`)
  await send.click()
  await page.getByRole('heading', { name: 'Thank you!' }).waitFor()
  await page.getByRole('button', { name: 'Back to Home' }).click()
  await email.fill(`${'a'.repeat(64)}@${'b'.repeat(63)}.${'c'.repeat(63)}.${'d'.repeat(62)}`)
  await send.click()
  await page.getByText('Email address must be 254 characters or fewer.').waitFor()
}
